# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区域')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='型号')),
                ('cpu', models.CharField(max_length=20, null=True, verbose_name='CPU')),
                ('RAM', models.CharField(max_length=20, null=True, verbose_name='内存')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IpInif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computer_name', models.CharField(max_length=30, verbose_name='计算机名')),
                ('ipad', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP地址')),
                ('macad', models.CharField(max_length=18, null=True, verbose_name='MAC地址')),
                ('openeye', models.IntegerField(null=True, verbose_name='OpenEye号')),
                ('seat', models.CharField(max_length=50, verbose_name='位置')),
                ('user', models.CharField(default='不固定', max_length=20, null=True, verbose_name='使用人')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='最后更新')),
                ('remark', models.TextField(null=True, verbose_name='备注')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipinfos', to='info.Area')),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ipinfos', to='info.Device')),
            ],
            options={
                'ordering': ['area', 'seat'],
            },
        ),
    ]
