# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='device',
            name='RAM',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='device',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ipinif',
            name='macad',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='MAC地址'),
        ),
        migrations.AlterField(
            model_name='ipinif',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='ipinif',
            name='user',
            field=models.CharField(default='不固定', max_length=20, verbose_name='使用人'),
        ),
    ]
