# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20180322_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipinif',
            name='openeye',
            field=models.IntegerField(blank=True, null=True, verbose_name='OpenEye号'),
        ),
    ]
